#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — LevelUp10: Supabase einrichten (Tag 1). Vercel/GitHub folgt an Tag 2.
# Aufruf im Projektordner (Git Bash):  bash scripts/setup-supabase.sh
# ──────────────────────────────────────────────────────────────────────────

cd "$(dirname "$0")/.."
ENV_FILE=".env.local"
TOTAL_STAGES=5

# clean VAR — entfernt Steuerzeichen (z. B. ^V, wenn in Git Bash Strg+V gedrückt wurde) und Leerraum am Rand.
clean() {
  local v
  v=$(printf '%s' "${!1}" | LC_ALL=C tr -d '\000-\037\177' | LC_ALL=C sed -e 's/\xc2[\x80-\x9f]//g' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
  printf -v "$1" '%s' "$v"
}

# need VAR "Prompt" secret? — fragt so lange, bis ein nicht leerer Wert da ist.
need() {
  while :; do
    if [[ "${3:-}" == secret ]]; then ask_secret "$1" "$2"; else ask "$1" "$2"; fi
    clean "$1"
    [[ -n "${!1}" ]] && return
    warn "Leer. Einfügen in Git Bash mit Rechtsklick oder Umschalt+Einfg, nicht mit Strg+V."
  done
}

banner "LevelUp10 · Supabase einrichten"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Supabase-Projekt anlegen"
open_url "https://supabase.com/dashboard/new"
step "Organisation wählen (oder anlegen, falls noch keine da ist)."
step "Project name: levelup10"
step "Database Password: ein starkes Passwort erzeugen und im Passwort-Manager speichern (wird hier nicht gebraucht)."
step "Region: Central EU (Frankfurt)."
step "Create new project klicken und warten, bis das Projekt bereit ist (1-2 Minuten)."
pause "Projekt ist bereit? Enter."

# ── 2 ────────────────────────────────────────────────────────────────────
stage "Projekt-ID und Schlüssel"
warn "Einfügen hier im Terminal: Rechtsklick oder Umschalt+Einfg (Strg+V fügt in Git Bash nicht ein)."
say "Die Projekt-ID steht in der Adresszeile des Dashboards:"
note "https://supabase.com/dashboard/project/<PROJEKT-ID>/..."
need SUPABASE_PROJECT_REF "Projekt-ID (nur der Teil nach /project/):"
SUPABASE_PROJECT_REF="${SUPABASE_PROJECT_REF//\//}"
write_env SUPABASE_PROJECT_REF "$SUPABASE_PROJECT_REF"
write_env NEXT_PUBLIC_SUPABASE_URL "https://${SUPABASE_PROJECT_REF}.supabase.co"
printf '\n'
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/settings/api-keys"
step "Seite Settings › API Keys. Falls dort noch keine Publishable- und Secret-Keys stehen: anlegen."
step "Publishable key kopieren (beginnt mit sb_publishable_)."
need NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "Publishable key einfügen:"
write_env NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY "$NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY"
step "Secret key aufdecken und kopieren (beginnt mit sb_secret_). Niemals weitergeben."
need SUPABASE_SECRET_KEY "Secret key einfügen (unsichtbar):" secret
write_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
pause "Weiter mit Enter."

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Datenbank-Tabellen anlegen (Migration)"
if command -v clip.exe >/dev/null 2>&1; then
  clip.exe < supabase/migrations/0001_init.sql
  say "Die Migration liegt jetzt in deiner Zwischenablage."
else
  warn "Zwischenablage nicht verfügbar. Öffne supabase/migrations/0001_init.sql und kopiere den ganzen Inhalt."
fi
open_url "https://supabase.com/dashboard/project/${SUPABASE_PROJECT_REF}/sql/new"
step "Im SQL Editor: Strg+V (ganzer Inhalt), dann Run klicken."
step "Erwartet: 'Success. No rows returned'. Bei einer Fehlermeldung hier abbrechen (Strg+C) und den Text an Claude geben."
pause "Migration ohne Fehler gelaufen? Enter."

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Accounts für Felix und dich"
say "Die Seed-Datei legt beide Logins an. Passwörter vergibst du hier."
need SEED_STUDENT_EMAIL "E-Mail für Felix:"
write_env SEED_STUDENT_EMAIL "$SEED_STUDENT_EMAIL"
need SEED_STUDENT_PASSWORD "Passwort für Felix (mind. 6 Zeichen, unsichtbar):" secret
write_env SEED_STUDENT_PASSWORD "$SEED_STUDENT_PASSWORD"
write_env SEED_STUDENT_NAME "Felix"
need SEED_PARENT_EMAIL "Deine E-Mail (Eltern-Login):"
write_env SEED_PARENT_EMAIL "$SEED_PARENT_EMAIL"
need SEED_PARENT_PASSWORD "Dein Passwort (mind. 6 Zeichen, unsichtbar):" secret
write_env SEED_PARENT_PASSWORD "$SEED_PARENT_PASSWORD"
write_env SEED_PARENT_NAME "Phil"
pause "Weiter mit Enter."

# ── 5 ────────────────────────────────────────────────────────────────────
stage "Aufgaben und Accounts laden (Seed)"
say "Lädt 360 Aufgaben (Mathe, BwR), den Schuljahres-Kalender und beide Accounts."
note "Kann jederzeit erneut laufen: npm run seed (ändert nur, was sich geändert hat)."
if confirm "Seed jetzt ausführen?"; then
  if npm run seed; then
    say "Seed fertig."
  else
    SKIPPED+=("Seed fehlgeschlagen: npm run seed erneut ausführen und die Ausgabe an Claude geben")
    warn "Seed fehlgeschlagen. Ausgabe oben an Claude geben."
  fi
else
  SKIPPED+=("npm run seed")
fi
pause "Weiter mit Enter."

finish
say "Lokal testen:  npm run dev   → http://localhost:3000   (als Felix einloggen)"
printf '\n'
